{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "activeUsers_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{method}} "
    }
   ]
  },
  {
   "title": "HTTP request/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(auth_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{method}} "
    }
   ]
  },
  {
   "title": "CPU and Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cpu_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "CPU"
    },
    {
     "expr": "memory_total{method=\"total\", source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Pizza purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(order_total{source=\"jwt-pizza-service\", method=\"failed\"}[1m])",
     "legendFormat": "Purchase failures"
    },
    {
     "expr": "rate(order_total{method=\"total\"}[1m])",
     "legendFormat": "Pizza purchases"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(revenue_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Revenue/minute"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "latency_latency{source=\"jwt-pizza-service\", method=\"apiauthPUT\"}",
     "legendFormat": "Login"
    },
    {
     "expr": "latency_latency{source=\"jwt-pizza-service\", method=\"apiordermenuGET\"}",
     "legendFormat": "Get Menu"
    },
    {
     "expr": "latency_latency{source=\"jwt-pizza-service\", method=\"apiauthDELETE\"}",
     "legendFormat": "Logout"
    },
    {
     "expr": "latency_latency{source=\"jwt-pizza-service\", method=\"apiorderPOST\"}",
     "legendFormat": "Pizza creation"
    }
   ]
  },
  {
   "title": "All Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "latency_latency{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{method}} "
    }
   ]
  }
 ]
}